Added NaiveBayes Model description.
v2msLabs/ML1000-1 pull request #4
Opened 2019-02-12 19:04 UTC by safzalm

2019-02-12 19:47 UTC, v2msLabs commented on source/main.Rmd
> +The Baive Bayes algorithm can be implemented using different packages (i.e. e1071, klaR, naivebayes) Here we are using the caret package.The caret package contains train() function which is helpful i
I would suggest to skip this paragraph. Actually caret employs klaR implementation. The rest is excellent

2019-02-12 19:51 UTC, v2msLabs requested changes
Please review my comment

2019-02-12 22:51 UTC, safzalm commented
NB Model description changed.

2019-02-12 23:07 UTC, safzalm commented
Please review the changes I made in NB Model description.

2019-02-13 00:44 UTC, closed without merging

2019-02-13 00:45 UTC, safzalm commented
I am closing this and creating new PR